#:kivy 2.1.0

<RoundedButton@Button>:
    background_normal: ''
    background_color: 0, 0, 0, 0
    font_size: '16sp'
    bold: True
    color: 0, 0, 0, 1
    on_press:
        self.opacity = 0.7
    on_release:
        self.opacity = 1
    canvas.before:
        Color:
            rgba: 0.85, 0.85, 0.85, 1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [25]